#!/bin/bash

if [ $1 == "voltage" ]; then
    dp832 :SOUR1:VOLT $2
elif [ $1 == "current" ]; then
    dp832 :SOUR1:CURR $2
elif [ $1 == "on" ]; then
    dp832 :OUTP CH1,ON
elif [ $1 == "off" ]; then
    dp832 :OUTP CH1,OFF
elif [ $1 == "reboot" ]; then
    dp832 off; sleep 0.3; dp832 on
else
    echo $@ | netcat 10.1.1.2 5555 -w0
fi