#!/bin/bash

log=`mktemp`
echo "Log in $log"
run=0

while true; do
    run=$((run+1))
    
    echo -n Run $run
    SECONDS=0
    tput sc
    $@ >> $log 2>&1 &

    while jobs %% >> /dev/null 2>&1; do
        tput rc
        echo -n " running for $SECONDS s..."
        sleep 0.1
    done

    RESULT=$?
    end=`date +%s`
    if [ $RESULT -eq 0 ]; then
        echo "pass"
    else
        echo "failed with exit code $RESULT"
        echo "Log in $log:"
        cat $log
        exit $RESULT
    fi
done