#!/bin/bash
set -euo pipefail

workers=$(expr $(cat /proc/cpuinfo | grep processor | wc -l) - 1)

mkdir -p ~/git/boomerang/build
cd ~/git/boomerang/build

cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=TRUE ../
cmake --build ./ --target data-link-usb-1.8-with-bootloader
skypi --udl flash ~/git/boomerang/build/devices/data-link-usb/data-link-usb-1.8-with-bootloader.bin
