#!/bin/bash
set -euo pipefail

URL=https://dist.internal.ara-uas.com/skymate/master/alpha/latest/skymate-v3.ara
FILE=`mktemp -d`/`basename $URL`
wget https://dist.internal.ara-uas.com/skymate/master/alpha/latest/skymate-v3.ara -O $FILE
skypi flash $FILE
