#!/bin/bash
set -euo pipefail

workers=$(expr $(cat /proc/cpuinfo | grep processor | wc -l) - 1)

mkdir -p ~/git/boomerang/build
cd ~/git/boomerang/build

cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=TRUE ../
cmake --build ./ --target base-station-1.0-with-bootloader
skypi --rtk flash ~/git/boomerang/build/devices/data-link-usb/base-station-1.0-with-bootloader.bin
