#!/bin/bash

columns=$(tput cols)
columnsMinus1="$(($columns-4))"
echo Columns minus is $columnsMinus1
while read -r line; do 
    tput sc
    printf '%-'"$columnsMinus1"'s' "$line" | cut -c-$columnsMinus1 | tr -d '\n'
    tput rc
done
echo
