#!/bin/bash
set -euxo pipefail

cd ~/git/boomerang
deploy/scripts/linux/ci_build.sh

if [ $# -eq 0 ]
  then
        deploy/scripts/linux/ci_run_integration_tests.sh
        deploy/scripts/linux/ci_run_requirements_tests.sh
        deploy/scripts/linux/ci_run_requirement_coverage.sh
        deploy/scripts/linux/ci_run_unit_tests.sh
else
    if [ "$1" = "i" ]
    then
        deploy/scripts/linux/ci_run_integration_tests.sh
    fi

    if [ "$1" = "r" ]
    then
        deploy/scripts/linux/ci_run_requirements_tests.sh
    fi

    if [ "$1" = "c" ]
    then
        deploy/scripts/linux/ci_run_requirement_coverage.sh
    fi

    if [ "$1" = "u" ]
    then
        deploy/scripts/linux/ci_run_unit_tests.sh
    fi

    if [ "$1" = "d" ]
    then
        deploy/scripts/linux/ci_run_skycontrol-lib_deploy_tests.sh
    fi
fi
